### ISSUE TITLE
Any chance we can get a .deb that can be installed on Ubuntu 22.04?

### ISSUE THREAD

**Issue by mdPlusPlus** [manuels/wireguard-p2p#13]
I got it to work by installing these three packages from bionic:

- https://packages.ubuntu.com/bionic/libffi6
- https://packages.ubuntu.com/bionic/libhogweed4
- https://packages.ubuntu.com/bionic/libnettle6

But there might be a reason why they haven't been included in newer LTS releases (focal and jammy).

It would be great if there was a plug-and-play solution for Ubuntu 22.04 ("jammy").

The following packages are available on jammy:

- libffi8
- libhogweed6
- libnettle8

Unfortunately I don't know whether their APIs are stable between major releases.

**Comment by manuels** [comment]
To be honest, I abandoned this project a while ago in favor of [Slack's nebula vpn](https://github.com/slackhq/nebula).

**Comment by mdPlusPlus** [comment]
Nebula unfortunately requires central *Lighthouses* and therefore isn't strictly decentralized. Plus AFAICT there are no installable packages released.

Any pointers into the right direction on how I could build the .debs with the newer libraries? I tried simply repackaging the .deb with a modified control file, which installs fine, but still looks for libffi.so.**6** instead of libffi.so.**8** on the system and therefore doesn't work.

Edit: I would try `cargo-deb`, but I can't get `cargo install wireguard-p2p` to succeed.

**Comment by manuels** [comment]
If I remember correctly, this is the Dockerfile I used to build the deb files. Maybe this gives you a clue how to cahnge it:

```
# DOCKER_BUILDKIT=1 docker build -f Dockerfile.build --output out .

FROM rust:1.43 AS build-stage

WORKDIR .

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y libopendht-dev llvm clang
RUN apt-get clean

RUN cargo install cargo-deb

COPY . .

RUN cargo install --path .
RUN cargo deb


FROM scratch AS export-stage
COPY --from=build-stage /usr/local/cargo/bin/wireguard-p2p /
COPY --from=build-stage target/debian /

```

What is the error message you get when running `cargo install wireguard-p2p`?

**Comment by mdPlusPlus** [comment]
When I issue `apt install -y libopendht-dev && cargo install wireguard-p2p` in the `rust:latest` docker container, it succeeds without issues.

My issue arised when trying the same on `ubuntu:jammy`, but it turns out I was missing the `build-essential` package and the cargo error message wasn't really clear on that.

I'm going to try to build the .deb now and will see whether they still require the outdated libs then.

Edit: Seems like it doesn't:

```
# apt show ./wireguard-p2p_0.3.0_amd64.deb

Package: wireguard-p2p
Version: 0.3.0
Priority: optional
Maintainer: Manuel Schölling <manuel.schoelling@posteo.de>
Installed-Size: 4009 kB
Depends: libjsoncpp24 (>= 1.9.4), libnettle8, libhttp-parser2.9 (>= 2.7.1), libgnutls30 (>= 3.7.0), libargon2-1 (>= 0~20171227), libstdc++6 (>= 9), libssl1.1 (>= 1.1.0), libc6 (>= 2.30)
Download-Size: 1241 kB
APT-Sources: /root/wireguard-p2p/target/debian/wireguard-p2p_0.3.0_amd64.deb
Description: A WireGuard peer-to-peer client
```
