### ISSUE TITLE
Error: "Unable to autolaunch a dbus-daemon without a $DISPLAY for X11"

### ISSUE THREAD

**Issue by adrianmihalko** [manuels/wireguard-p2p#2]
Hi manuels,

I installed wireguard-p2p on Ubuntu 16.04, but when I try to launch I get the error above. I am running a headless system, why wireguard-p2p needs a X11 component?

**Comment by adrianmihalko** [comment]
Some hours later I found that I need to install dbus-x11 package:

```
user@ubuntu:~$ apt install dbus-x11
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  dbus-x11
```

Now I have  dbus-launch command and I can run wireguard-p2p, but I still have problem, because publish command is not working:

```
user@ubuntu:~$ dbus-launch /home/user/.cargo/bin/wireguard-p2p publish wg0 myserver_sk
[sudo] password for user: 
user@ubuntu:~$ /home/user/.cargo/bin/wireguard-p2p publish wg0 myserver_sk
Error: "Unable to autolaunch a dbus-daemon without a $DISPLAY for X11"
user@ubuntu:~$ dbus-launch /home/user/.cargo/bin/wireguard-p2p publish wg0 myserver_sk
user@ubuntu:~$ dbus-launch wireguard-p2p search myserver_sk
No public keys found for 'myserver_sk'!

```

**Comment by manuels** [comment]
Hi @adrianmihalko,

sorry, github just sent me a mail for this bug.
Did you install [bulletinboard-dht](https://github.com/manuels/bulletinboard-dht/)?

**Comment by adrianmihalko** [comment]
Yes, like it's in the readme:

  # Debian/Ubuntu
  wget 'https://github.com/manuels/bulletinboard-dht/releases/download/v0.5.3/bulletinboard_0.5.3_amd64.deb'
sudo dpkg -i bulletinboard_0.5.3_amd64.deb

I tried to install on two Ubuntu system, result is the same. I can run wireguard-p2p via dbus-launch command, but for publish command I get empty output. 🤔

**Comment by adrianmihalko** [comment]
If I try to run bulletinboard manually:

```
$ bulletinboard 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I think this is the problem? wireguard-p2p tries to run bulletinboard, but because the problem with dbus can't run it. 

Ok, but what's this dbus is all about and how can I resolve? I don't have X11 on my headless servers.

**Comment by manuels** [comment]
Ok, now I get it: wireguard-p2p communicates with bulletinboard via Dbus. If dbus is not installed, bulletinboard cannot run, of course.

There has been the suggestion to get rid of dbus https://github.com/manuels/bulletinboard-dht/issues/4, but I am refactoring bulletinboard to work with futures v0.2 right now...

**Comment by adrianmihalko** [comment]
Thank you, I'll wait then. ✋👍

**Comment by adrianmihalko** [comment]
@manuels any info on this?

**Comment by manuels** [comment]
I'm afraid no. Rust is still working on proper futures and tokio support. Currently it is in a big refactoring phase and I will wait until this is done to continue with wireguard-p2p development.

**Comment by manuels** [comment]
I just pushed a new version that does not need dbus but opendht.

**Comment by adrianmihalko** [comment]
Cool, can you please build a .deb?

**Comment by AfnanCSE98** [comment]
Has anyone found a way around?

**Comment by manuels** [comment]
This bug is closed and should be resolved. Are you still running into this issue?
